name: Render and Publish
on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          tinytex: true
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # - name: Install Chrome
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y google-chrome-stable
      # - name: Render Quarto pdf course_day_1.qmd
      #   uses: quarto-dev/quarto-actions/render@v2
      #   with:
      #     path: course_day_1.qmd
      #     to: pdf
      - name: Render Quarto pdf course_day_2.qmd
        uses: quarto-dev/quarto-actions/render@v2
        with:
          path: course_day_2.qmd
          to: pdf
      # - name: Render Quarto html course_day_1
      #   uses: quarto-dev/quarto-actions/render@v2
      #   with:
      #     path: course_day_1.qmd
      #     to: revealjs
      - name: Render Quarto html course_day_2
        uses: quarto-dev/quarto-actions/render@v2
        with:
          path: course_day_2.qmd
          to: revealjs
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Rendered Quarto files"
          commit_options: "--no-verify"
          branch: main